name: Pull docker and packages
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        mkdir packages
        cd packages
        sudo bash ../add-repositories.sh
        sudo apt --download-only install libtool make cmake libseccomp-dev gcc python3 python3-venv golang-1.22-go temurin-21-jdk nodejs strace ca-certificates curl gnupg 
        sudo apt --download-only install build-essential libmpfr-dev libgmp3-dev libmpc-dev -y
        wget http://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.gz
    - name: Archive Release 1
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'packages.1'
        path: ./packages
    - name: Archive Release 1
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'packages.2'
        path: /var/cache/apt/archives        
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages.1
          packages.2
        tag_name: ${{ github.event.inputs.tags }}
