name: Pull docker and packages
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        mkdir packages
        cd packages
        sudo bash ../add-repositories.sh
        sudo apt -d build-dep libtool make cmake libseccomp-dev gcc python3 python3-venv python3.12-minimal python3.12-venv libpython3.12-stdlib libpython3.12-dev golang-1.22-go temurin-21-jdk gcc-13 g++-13 nodejs strace ca-certificates curl gnupg
    - name: Archive Release 1
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'packages.1'
        path: ./packages
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages.1
        tag_name: ${{ github.event.inputs.tags }}
