name: Pull docker and packages
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        mkdir packages
        cd packages
        sudo bash ../add-repositories.sh
        sudo apt -d install libtool make cmake libseccomp-dev -y --reinstall
        sudo apt -d install gcc python3 python3-venv golang-1.22-go temurin-21-jdk nodejs strace ca-certificates curl gnupg -y --reinstall
        sudo apt -d install build-essential libmpfr-dev libgmp3-dev libmpc-dev -y --reinstall
        sudo apt -d install python3.10 python3.10-venv lsb-release --reinstall
    - name: Archive Release packages
      shell: bash
      run: |
        sudo 7z a -m0=lzma2 -mx packages.2 "/var/cache/apt/archives"
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages.1
          packages.2
        tag_name: ${{ github.event.inputs.tags }}
