name: Pull docker and packages
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        mkdir packages
        cd packages
        sort -u ../packages.list | xargs sudo apt-get download && dpkg-scanpackages ./ /dev/null | gzip -9c > ./Packages.gz
    - name: Archive Release packages
      shell: bash
      run: |
        tar -cvf packages.z packages/
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages.z
        tag_name: ${{ github.event.inputs.tags }}
