name: Pull docker and packages
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        mkdir packages
        cd packages
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo curl -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo gpg --dearmor -o /etc/apt/keyrings/adoptium.gpg
        sudo cat > /etc/apt/sources.list.d/adoptium.sources <<EOF
        Types: deb
        URIs: https://packages.adoptium.net/artifactory/deb
        Suites: bookworm
        Components: main
        Signed-By: /etc/apt/keyrings/adoptium.gpg
        EOF
        sudo curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        sudo cat > /etc/apt/sources.list.d/nodesource.sources <<EOF
        Types: deb
        URIs: https://deb.nodesource.com/node_20.x
        Suites: nodistro
        Components: main
        Signed-By:/etc/apt/keyrings/nodesource.gpg
        EOF
        sudo apt-get update        
        sudo apt -d build-dep libtool make cmake libseccomp-dev gcc python3 python3-venv python3.12-minimal python3.12-venv libpython3.12-stdlib libpython3.12-dev golang-1.22-go temurin-21-jdk gcc-13 g++-13 nodejs strace ca-certificates curl gnupg
    - name: Archive Release 1
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'packages.1'
        path: ./packages
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages.1
        tag_name: ${{ github.event.inputs.tags }}
