name: DN upload
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        Invoke-WebRequest https://aka.ms/wslubuntu2204 -OutFile wslubuntu2204
    - name: Run
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m wslubuntu2204.z wslubuntu2204
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          wslubuntu2204.*
        tag_name: ${{ github.event.inputs.tags }}
