name: DN upload
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        Invoke-WebRequest https://master.dl.sourceforge.net/project/bleachbit/bleachbit/4.6.0/BleachBit-4.6.0-setup.exe?viasf=1 -OutFile BleachBit-4.6.0-setup
    - name: Run
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m BleachBit-4.6.0-setup.z BleachBit-4.6.0-setup
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          BleachBit-4.6.0-setup.z.*
        tag_name: ${{ github.event.inputs.tags }}
