name: DN upload
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        Invoke-WebRequest https://releases.ubuntu.com/22.04.6/ubuntu-22.04.6-desktop-amd64.iso -OutFile ubuntu-22.04.6-desktop-amd64.iso
    - name: Run
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m ubuntu-22.04.6-desktop-amd64.iso.z ubuntu-22.04.6-desktop-amd64.iso
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ubuntu-22.04.6-desktop-amd64.iso.z.*
        tag_name: ${{ github.event.inputs.tags }}
