name: DN upload
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        Invoke-WebRequest https://github.com/vertexi/ImMathWriter/releases/download/0.0.1/texocr-0.0.1.7z -OutFile texocr
    - name: Run
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m texocr.z texocr
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          texocr.*
        tag_name: ${{ github.event.inputs.tags }}
