name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull ghcr.io/matatonic/openedai-speech:latest
        docker save ghcr.io/matatonic/openedai-speech:latest | gzip > openedai-speech.gz
        7z a -t7z -mx -m0=LZMA2 -v40m openedai-speech.7z openedai-speech.gz
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          openedai-speech.7z*
        tag_name: ${{ github.event.inputs.tags }}
