name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull vnoj/judge-tiervnoj
        docker save vnoj/judge-tiervnoj | gzip > vnoj-tiervnoj.gz
        7z a -t7z -mx -m0=LZMA2 -v40m vnoj-tiervnoj.7z vnoj-tiervnoj.gz
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          vnoj-tiervnoj.7z*
        tag_name: ${{ github.event.inputs.tags }}
