name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_rsync
        docker save --output oj_rsync.tar registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_rsync
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          oj_rsync.tar
        tag_name: ${{ github.event.inputs.tags }}
