name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull typesense/docsearch-scraper:0.11.0
        docker save typesense/docsearch-scraper:0.11.0 | gzip > typesense-docsearch-scraper-0.11.0.gz
        7z a -t7z -mx -m0=LZMA2 -v40m typesense-docsearch-scraper-0.11.0.7z typesense-docsearch-scraper-0.11.0.gz
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          typesense-docsearch-scraper-0.11.0.7z*
        tag_name: ${{ github.event.inputs.tags }}
