name: Pull large docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
      image:
        description: 'image to download'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        name=$(basename '${{ github.event.inputs.image }}')
        python pull-docker.py ${{ github.event.inputs.image }} 
        7z a -t7z -mx -m0=LZMA2 -v40m $name.7z *.tar
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.7z*
        tag_name: ${{ github.event.inputs.tags }}
