name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull dmoj/runtimes-tier1
        docker save --output dmoj-runtimes-tier1.tar dmoj/runtimes-tier1
        docker pull dmoj/runtimes-tier2
        docker save --output dmoj-runtimes-tier2.tar dmoj/runtimes-tier2
        docker pull dmoj/runtimes-tier3
        docker save --output dmoj-runtimes-tier3.tar dmoj/runtimes-tier3
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar
        tag_name: ${{ github.event.inputs.tags }}
