name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull ubuntu:22.04
        docker save ubuntu:22.04 | gzip > ubuntu-22.04.gz
        7z a -t7z -mx -m0=LZMA2 -v40m ubuntu-22.04.7z ubuntu-22.04.gz
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ubuntu-22.04.7z*
        tag_name: ${{ github.event.inputs.tags }}
