name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull gitea/act_runner:latest
        docker save --output dmoj-judge-tier3.tar dmoj/judge-tier3:latest
        7z a -t7z -mx -m0=LZMA2 -v40m dmoj-judge-tier3.7z dmoj-judge-tier3.tar
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dmoj-judge-tier3.7z*
        tag_name: ${{ github.event.inputs.tags }}
