name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
      image:
        description: 'image to download'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        $name = $(basename ${{ github.event.inputs.image }})
        docker pull ${{ github.event.inputs.image }} 
        docker save ${{ github.event.inputs.image }} | gzip > $name.gz
        7z a -t7z -mx -m0=LZMA2 -v40m $name.7z $name.gz
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.7z*
        tag_name: ${{ github.event.inputs.tags }}
