name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull postgres:16-alpine
        docker save --output postgres-16.tar postgres:16-alpine
        docker pull docker.io/bitnami/mysql:5.7
        docker save --output mysql-5.7.tar docker.io/bitnami/mysql:5.7
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar
        tag_name: ${{ github.event.inputs.tags }}
