name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull penpotapp/backend
        docker save penpotapp/backend | gzip > penpotapp-backend.gz
        7z a -t7z -mx -m0=LZMA2 -v40m penpotapp-backend.7z penpotapp-backend.gz
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          penpotapp-backend.7z*
        tag_name: ${{ github.event.inputs.tags }}
