name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull docs/docker.github.io:latest
        docker save --output docker-doc.tar docs/docker.github.io:latest
        7z a -m0=lzma2 -mx docker-doc.7z docker-doc.tar
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          docker-doc.7z
        tag_name: ${{ github.event.inputs.tags }}
