name: Pull docker
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        docker pull node:10.21.0
        docker save --output node-10.21.0.tar node:10.21.0
        7z a -m0=lzma2 -mx node-10.21.0.7z node-10.21.0.tar
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          node-10.21.0.7z
        tag_name: ${{ github.event.inputs.tags }}
