name: pull-ollama-llm
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache    
    - uses: actions/checkout@v3
    - name: download
      run: |
        pip install httpx rich
        python ollama-dl.py gemma3:4b -d models
    - run: |
        sudo 7z a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m gemma3-4b.tar.gz models
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          gemma3-4b.tar.gz.*
        tag_name: ${{ github.event.inputs.tags }}
      

      
