name: pull-ollama-llm
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache    
    - uses: actions/checkout@v3
    - name: download
      run: |
        pip install httpx rich
        python ollama-dl.py qwen3:30b-a3b -d models
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          models/blobs/*
        tag_name: ${{ github.event.inputs.tags }}
      

      
