name: pull-ollama-llm
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main    
    - name: Install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh
    - name: Run ollama and pull
      run: 
        ollama pull llama3.1
    - name: zip file
      run: |
        sudo 7z a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v20m x.tar.gz /usr/share/ollama
        git checkout -b feature/with-model
        git commit -am "with model"
        git push -u origin HEAD
    - name: List files
      run: |
          ls -a
          ls -R /usr/share/ollama
      

      
