name: pull-ollama-llm
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh
    - name: load model
      run: ollama pull llama3.1
    - uses: actions/checkout@v3
    - run: |
        sudo 7z a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v20m x.tar.gz /usr/share/ollama
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push -u origin HEAD
    - name: List files
      run: |
          ls -a
          ls -R /usr/share/ollama
      

      
