name: pull-ollama-llm
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: install ollama
      run: |
        curl -L https://ollama.com/download/ollama-linux-amd64.tgz -o ollama-linux-amd64.tgz
        sudo tar -C /usr -xzf ollama-linux-amd64.tgz
    - name: load model
      run: ollama pull qwen2.5-coder:7b-instruct
    - uses: actions/checkout@v3
    - run: |
        sudo 7z a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m x.tar.gz /usr/share/ollama/.ollama
    - name: List files
      run: |
          ls -a
          ls -R /usr/share/ollama
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          x.tar.gz.*
        tag_name: ${{ github.event.inputs.tags }}
      

      
