name: Create Archive
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Run
      run: |
        Invoke-WebRequest https://get.enterprisedb.com/postgresql/postgresql-16.2-1-windows-x64.exe -OutFile pgoutfile
        Invoke-WebRequest https://cdn.mysql.com//Downloads/MySQLInstaller/mysql-installer-community-8.0.32.0.msi -OutFile msoutfile
        Invoke-WebRequest https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi -OutFile crfile
    - name: Archive Release 1
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        path: 'pgoutfile'
        filename: 'pgoutfile.1'
    - name: Archive Release 2
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        path: 'msoutfile'
        filename: 'msoutfile.1'
    - name: Archive Release 3
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        path: 'crfile'
        filename: 'crfile.1'
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          pgoutfile.1
          msoutfile.1
          crfile.1
        tag_name: ${{ github.event.inputs.tags }}
